### ISSUE TITLE
Issue Report: File excluded issue

### ISSUE THREAD

**Issue by MarinBuric** [glenn2223/vscode-live-sass-compiler#253] opened 2023-01-10 12:30 UTC
_**Edit:** it is seeming to be an issue_

Hello, ~this is more a cry for help then an issue report :) - so~ if you can help me I would appreciate.

I'm receiving this popular error:
```
Checking current file
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
File excluded
The file is excluded based on your settings, please check your configuration
--------------------
```

But when I run Compile Current Sass file - my file is compiled in savePath folder.

I have all settings in the .code-workspace file. The workspace is multi-root with 3 folders like this and for easier maintenance, all settings are here, like this:

```JS
{
	"folders": [
		{ "path": "\\\\xxx.evdev.net\\_catalogs\\masterpage"	},
		{ "path": "\\\\xxx.evdev.net\\_catalogs\\wp"		},
		{ "path": "\\\\xxx.evdev.net\\style library" }
	],
	"settings": {
		"liveSassCompile.settings.watchOnLaunch": true,
		"liveSassCompile.settings.compileOnWatch": true,
		"liveSassCompile.settings.excludeList": [
			"/**/node_modules/**",
			"/.vscode/**",
		],
		"liveSassCompile.settings.formats":[
			{
				"format":           "expanded",
				"extensionName":    ".css",
				"savePath":         "/Assets/cssprod/test"
			}
		],
		"liveSassCompile.settings.generateMap": true,
		"liveSassCompile.settings.forceBaseDirectory": null
		}
}
```

The same error happens if I move `excludeList` and `formats` to settings.json in the MasterPage folder and even if I delete `excludeList` property. Of course, everything was working with the previous extension.

Any idea?
Thank you
Marin

**Comment by glenn2223** [comment] 2023-01-10 13:32
The `Compile Current Sass File` ignores the exclude settings - which must be the cause.

Can you run `liveSass.command.debugFileList` and see if that helps you?

If it doesn't, paste that output into a new comment here. Then also:
1. set [liveSassCompile.settings.showOutputWindowOn](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon) to `Trace`
2. repeat the steps to recreate the issue
3. paste that output here too

**Comment by MarinBuric** [comment] 2023-01-10 14:31
Thx, this is the output after saving the main scss file.


VS Code event: "onDidSaveTextDocument"
--------------------
Found the workspace folder
Workspace Name: masterpage
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Checking SASS path isn't excluded
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
Search results
Path: \\xxxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
  isMatch: true
   - Base path: \\xxx.evdev.net\_catalogs\masterpage
   - Rela path: Assets\css\_sp-library-tile-view.scss
  compare: false
   - Orig file path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
   - Orig sass path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
_**File not found, must be excluded**_ - to what file is this referring? 
--------------------
File excluded
The file has not been compiled as it's excluded by user settings
Path: \\graweintranet.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------


This "_sp-library" is just another partial scss file in the project. I don't see anything different from the other files.

**Comment by glenn2223** [comment] 2023-01-10 14:42
Is that the whole output? If so, `fdir` is only finding one file in that entire workspace folder.

Can I have the output from `liveSass.command.debugFileList` too?

**Comment by glenn2223** [comment] 2023-01-10 14:51
> _**File not found, must be excluded**_ - to what file is this referring?

It's not found `\\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss` because comparing the one file in your output returned false (as below)

>```
>  compare: false   <= THIS BIT
>   - Orig file path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
>   - Orig sass path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss 
>```

**Comment by MarinBuric** [comment] 2023-01-10 14:54
Here is debug output - nothing special inside 

```
Command called: "liveSass.command.debugFileList"
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/_*.s[ac]ss
Can be overwritten: false
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/_*.s[ac]ss
Can be overwritten: false
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/_*.s[ac]ss
Can be overwritten: false
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/node_modules/**,/.vscode/**
Can be overwritten: false
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/node_modules/**,/.vscode/**
Can be overwritten: false
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/node_modules/**,/.vscode/**
Can be overwritten: false
--------------------
Checking folder 1 of 3
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 3
Folder: wp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 3 of 3
Folder: style library
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Found 0 SASS files
--------------------
Found 0 SASS files
--------------------
Extension Info
--------------------
Current File
--------------------
\\graweintranet.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
Workspace Folders
--------------------
[0] masterpage
\\graweintranet.evdev.net\_catalogs\masterpage
[1] wp
\\graweintranet.evdev.net\_catalogs\wp
[2] style library
\\graweintranet.evdev.net\style library\
--------------------
Checking workspace folder 1 of 3
Path: \\graweintranet.evdev.net\_catalogs\masterpage
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
Checking workspace folder 2 of 3
Path: \\graweintranet.evdev.net\_catalogs\wp
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
Checking workspace folder 3 of 3
Path: \\graweintranet.evdev.net\style library\
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------

```

**Comment by MarinBuric** [comment] 2023-01-10 15:01
> 

> > _**File not found, must be excluded**_ - to what file is this referring?
> 
> It's not found `\\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss` because comparing the one file in your output returned false (as below)
> 
> > ```
> >  compare: false   <= THIS BIT
> >   - Orig file path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
> >   - Orig sass path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss 
> > ```

Of course, but why is he comparing two different files? I'm only editing Intranet.scss and on file save - it should compile. And I even removed that "sp-library" form project and I've add it back, but empty.

**Comment by glenn2223** [comment] 2023-01-10 16:45
`fdir` is searching the whole workspace folder for SASS files - that's why I was surprised that only one file was in the output. There should be as many comparisons as there are SASS files in your project. Was that the complete output from setting `liveSassCompile.settings.showOutputWindowOn` to `Trace`?

**Comment by glenn2223** [comment] 2023-01-10 17:25
>Of course, everything was working with the previous extension

Can you confirm that you have disabled/removed the old extension? There have been various reports of different issues when both are running.

**Comment by MarinBuric** [comment] 2023-01-11 11:48
> > Of course, everything was working with the previous extension
> 
> Can you confirm that you have disabled/removed the old extension? There have been various reports of different issues when both are running.

The old version was removed from VS, but files existed in %USERPROFILE%\.vscode\extensions .. so I deleted them. I've also removed "glenn2223.live-sass-5.5.1" folder which is your version and installed it again, but the same thing.

**Comment by glenn2223** [comment] 2023-01-11 12:17
I identified an issue with the `debugFileList` command a while ago. I have fixed ready to go for 5.5.2 (though I can't release it yet as I need to write up some doc changes).

There's an alpha available below - you can also choose to fork and package the `ahead` branch yourself.  
Can you drag this into the extension sidebar to install it? After that see if the dependency bumps have fixed your issue (as `fdir` has been bumped from 5.2 to 5.3). If not, try the `debugFileList` command again.

[live-sass-5.5.2-alpha.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/10392161/live-sass-5.5.2-alpha.1.zip)

**Comment by MarinBuric** [comment] 2023-01-11 12:36
This is output with alpha version, now I have only one folder in workspace for easier debug

```
Command called: "liveSass.command.debugFileList"
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/_*.s[ac]ss
Can be overwritten: false
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 1 SASS files
--------------------
Getting SASS files
Query pattern: /**/node_modules/**,/.vscode/**
Can be overwritten: false
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Extension Info
--------------------
Current File
--------------------
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
Workspace Folders
--------------------
[0] masterpage
\\xxx.evdev.net\_catalogs\masterpage
--------------------
Checking workspace folder 1 of 1
Path: \\xxx.evdev.net\_catalogs\masterpage
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
--------------------
Included Partial SASS Files
--------------------
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
--------------------
Excluded SASS Files
--------------------
--------------------

```

**Comment by glenn2223** [comment] 2023-01-11 15:20
Seems like it might be an issue with `fdir`.

So I can open an issue there, to get some assistance, can I have a screenshot of the folder structure (including the two [or more] SASS files)?

**Comment by glenn2223** [comment] 2023-01-11 17:35
Also, in addition to the above, can you include the trace log from alpha 2 (below)? I have expanded a trace log for some extra debugging

[live-sass-5.5.2-alpha.2.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/10394658/live-sass-5.5.2-alpha.2.zip)

**Comment by glenn2223** [comment] 2023-01-12 10:53
Thanks for the extra info, glad you can work with it until the issue is fixed.

Just added an extra check to see if an error is being thrown and suppressed - this will add some extra output to the trace log. So, if you don't mind, can you drag the below version into the extension tab, replicate the issue and post the output here?

[live-sass-5.5.2-alpha.3.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/10400812/live-sass-5.5.2-alpha.3.zip)

**Comment by MarinBuric** [comment] 2023-01-12 11:15
```
Command called: "liveSass.command.debugFileList"
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/_*.s[ac]ss
Can be overwritten: false
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 1 SASS files
--------------------
Getting SASS files
Query pattern: /**/node_modules/**,/.vscode/**
Can be overwritten: false
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Extension Info
--------------------
Current File
--------------------
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
Workspace Folders
--------------------
[0] masterpage
\\xxx.evdev.net\_catalogs\masterpage
--------------------
Checking workspace folder 1 of 1
Path: \\xxx.evdev.net\_catalogs\masterpage
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
--------------------
Included Partial SASS Files
--------------------
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
--------------------
Excluded SASS Files
--------------------
--------------------

```

it looks same as before.

**Comment by glenn2223** [comment] 2023-01-12 12:48
Hmm, strange. It doesn't seem to be updating when you're dragging it into VS code. Can you uninstall then drag alpha 3 in?

Sorry to be a pain

**Comment by MarinBuric** [comment] 2023-01-12 12:58
Here it is
![image](https://user-images.githubusercontent.com/52964255/212071389-43d07746-1853-4166-8499-7a6380aba444.png)

```
Command called: "liveSass.command.debugFileList"
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Getting SASS files
Query pattern: /**/_*.s[ac]ss
Can be overwritten: false
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 1 SASS files
--------------------
Getting SASS files
Query pattern: /**/node_modules/**,/.vscode/**
Can be overwritten: false
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Extension Info
--------------------
Current File
--------------------
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
Workspace Folders
--------------------
[0] masterpage
\\xxx.evdev.net\_catalogs\masterpage
--------------------
Checking workspace folder 1 of 1
Path: \\xxx.evdev.net\_catalogs\masterpage
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
--------------------
Included Partial SASS Files
--------------------
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
--------------------
Excluded SASS Files
--------------------
--------------------
```

it's the same .. but, this one has fdir output - this is on autosave document when it should compile everything

```
VS Code event: "onDidSaveTextDocument"
--------------------
Found the workspace folder
Workspace Name: masterpage
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Checking SASS path isn't excluded
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
No base folder override found. Keeping workspace folder
--------------------
Picomatch Result
Found: true
Path: Assets\css\intranet.scss
--------------------
Searching folder
**fdir** Output
["\\\\xxx.evdev.net\\_catalogs\\masterpage\\Assets\\css\\_sp-library-tile-view.scss"]
--------------------
Search results
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
  isMatch: true
   - Base path: \\graweintranet.evdev.net\_catalogs\masterpage
   - Rela path: Assets\css\_sp-library-tile-view.scss
  compare: false
   - Orig file path: \\graweintranet.evdev.net\_catalogs\masterpage\Assets\css\_sp-library-tile-view.scss
   - Orig sass path: \\graweintranet.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
File not found, must be excluded
--------------------
File excluded
The file has not been compiled as it's excluded by user settings
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
```

**Comment by glenn2223** [comment] 2023-01-12 13:03
Sorry, yeah, complete brain fart. I meant to recreate the issue, not run the command - I didn't even process the top line of the output 🤦‍♂️

Thanks, the latter is the output I needed

**Comment by glenn2223** [comment] 2023-01-24 09:54
There have been a few reports of issues over network drives. Can you try VS Code server, as per my comment over at https://github.com/glenn2223/vscode-live-sass-compiler/discussions/254#discussioncomment-4715857

**Comment by glenn2223** [comment] 2023-02-07 13:03
Closing as info required

**Closed by glenn2223** 2023-02-07 13:03 UTC
Labels: bug, info required

**Comment by MarinBuric** [comment] 2023-02-14 12:31
hello @glenn2223  -  it looks like everything works fine now with v6.0.2 I've tried with VS Tunnels and https - but didn't have time to dig into that solution.

And today, after the update I decided to try again and here it is - changes are made in __intranet-rendition-img-fluid.sass_ - and sass was compiled to the new folder Test3.

It takes some time while "Working on it" status - but it could be due to the Sass2.0 warnings.

Thank you.

```
VS Code event: "onDidSaveTextDocument"
--------------------
Found the workspace folder
Workspace Name: masterpage
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Checking SASS path isn't excluded
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_intranet-rendition-img-fluid.scss
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
Search results
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-rating.scss
  isMatch: true
   - Base path: \\xxx.evdev.net\_catalogs\masterpage
   - Rela path: Assets\css\_sp-rating.scss
  compare: false
   - Orig file path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-rating.scss
   - Orig sass path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_intranet-rendition-img-fluid.scss
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-topnavigation.scss
  isMatch: true
   - Base path: \\xxx.evdev.net\_catalogs\masterpage
   - Rela path: Assets\css\_sp-topnavigation.scss
  compare: false
   - Orig file path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_sp-topnavigation.scss
   - Orig sass path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\_intranet-rendition-img-fluid.scss

ETC ETC ETC
ETC ETC
ETC 

--------------------
File found, not excluded
--------------------
Changing status bar to: "Working on it..."
--------------------
Change detected - 2/14/2023, 12:54:12 PM
_intranet-rendition-img-fluid.scss
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: masterpage
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 4 SASS files
--------------------
Compiling Sass/Scss Files: 
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-grid.scss
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap.scss
\\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-reboot.scss
--------------------
Starting file 1 of 4
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
Found the workspace folder
Workspace Name: masterpage
--------------------
Starting format 1 of 1
Settings: {"format":"expanded","extensionName":".css","savePath":"/Assets/cssprod/test3"}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
No workspace provided
Using originating path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
Using `savePath` setting
This format has a `savePath`, using this (takes precedence if others are present)
savePath: /Assets/cssprod/test3
--------------------
Path is relative to workspace folder
No tilde so the path is relative to the workspace folder being used
Original path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
Path to continue with: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3
--------------------
Checking directory exists
Directory: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3
Directory doesn't exist, creating it
--------------------
Starting file 2 of 4
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-grid.scss
--------------------
Found the workspace folder
Workspace Name: masterpage
--------------------
Starting format 1 of 1
Settings: {"format":"expanded","extensionName":".css","savePath":"/Assets/cssprod/test3"}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-grid.scss
--------------------
No workspace provided
Using originating path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-grid.scss
--------------------
Using `savePath` setting
This format has a `savePath`, using this (takes precedence if others are present)
savePath: /Assets/cssprod/test3
--------------------
Path is relative to workspace folder
No tilde so the path is relative to the workspace folder being used
Original path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-grid.scss
Path to continue with: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3
--------------------
Checking directory exists
Directory: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3
Directory exists, no action required
--------------------
Starting file 3 of 4
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap.scss
--------------------
Found the workspace folder
Workspace Name: masterpage
--------------------
Starting format 1 of 1
Settings: {"format":"expanded","extensionName":".css","savePath":"/Assets/cssprod/test3"}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap.scss
--------------------
No workspace provided
Using originating path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap.scss
--------------------
Using `savePath` setting
This format has a `savePath`, using this (takes precedence if others are present)
savePath: /Assets/cssprod/test3
--------------------
Path is relative to workspace folder
No tilde so the path is relative to the workspace folder being used
Original path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap.scss
Path to continue with: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3
--------------------
Checking directory exists
Directory: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3
Directory exists, no action required
--------------------
Starting file 4 of 4
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-reboot.scss
--------------------
Found the workspace folder
Workspace Name: masterpage
--------------------
Starting format 1 of 1
Settings: {"format":"expanded","extensionName":".css","savePath":"/Assets/cssprod/test3"}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-reboot.scss
--------------------
No workspace provided
Using originating path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-reboot.scss
--------------------
Using `savePath` setting
This format has a `savePath`, using this (takes precedence if others are present)
savePath: /Assets/cssprod/test3
--------------------
Path is relative to workspace folder
No tilde so the path is relative to the workspace folder being used
Original path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-reboot.scss
Path to continue with: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3
--------------------
Checking directory exists
Directory: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3
Directory exists, no action required
--------------------
Starting compilation
Starting compilation of file
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
Autoprefixer isn't false, applying to file
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\intranet.scss
--------------------
Preparing autoprefixer
--------------------
Starting autoprefixer
--------------------
Starting compilation
Starting compilation of file
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-grid.scss
--------------------
	...some warnings here THIS IS DEPRECATED AND WILL BE REMOVED IN SASS 2.0
--------------------
Warning:
2 repetitive deprecation warnings omitted.
null
--------------------
Autoprefixer isn't false, applying to file
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-grid.scss
--------------------
Preparing autoprefixer
--------------------
Starting autoprefixer
--------------------
Starting compilation
Starting compilation of file
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap.scss
--------------------
Warning:
 .. some warnings THIS IS DEPRECATED AND WILL BE REMOVED IN SASS 2.0
--------------------
Warning:
35 repetitive deprecation warnings omitted.
null
--------------------
Autoprefixer isn't false, applying to file
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap.scss
--------------------
Preparing autoprefixer
--------------------
Starting autoprefixer
--------------------
Starting compilation
Starting compilation of file
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-reboot.scss
--------------------
Autoprefixer isn't false, applying to file
Path: \\xxx.evdev.net\_catalogs\masterpage\Assets\css\bootstrap\bootstrap-reboot.scss
--------------------
Preparing autoprefixer
--------------------
Starting autoprefixer
--------------------
Completed autoprefixer
--------------------
Completed autoprefixer
--------------------
Completed autoprefixer
--------------------
Completed autoprefixer
--------------------
Saving file
Saving a file to the system
Target: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\intranet.css.map
--------------------
Saving file
Saving a file to the system
Target: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\intranet.css
--------------------
Saving file
Saving a file to the system
Target: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap-grid.css.map
--------------------
Saving file
Saving a file to the system
Target: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap-grid.css
--------------------
Saving file
Saving a file to the system
Target: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap.css.map
--------------------
Saving file
Saving a file to the system
Target: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap.css
--------------------
Saving file
Saving a file to the system
Target: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap-reboot.css.map
--------------------
Saving file
Saving a file to the system
Target: \\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap-reboot.css
--------------------
Generated:
\\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap-grid.css.map
\\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap-grid.css
--------------------
Generated:
\\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\intranet.css.map
\\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\intranet.css
--------------------
Generated:
\\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap.css.map
\\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap.css
--------------------
Generated:
\\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap-reboot.css.map
\\xxx.evdev.net\_catalogs\masterpage\Assets\cssprod\test3\bootstrap-reboot.css
--------------------
Changing status bar to: Success
Registered timeout to switch state back
--------------------
Registered timeout to revert UI to correct watching status
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
Firing timeout function to switch back
--------------------
Changing status bar to: Watching
--------------------
```

**Comment by glenn2223** [comment] 2023-02-14 12:35
Glad it works, must have been something sorted in one of the recent SASS/fdir updates. YAY!!!!!

**Comment by MarinBuric** [comment] 2023-02-14 12:39
I've fixed all Sass warnings and it compiles pretty fast.

Thx again
