### ISSUE TITLE
Media Query Group

### ISSUE THREAD

**Issue by mediafoks** [glenn2223/vscode-live-sass-compiler#152] opened 2022-01-30 07:04 UTC
Is there a setting to merge all identical the media queries into 1 media query?

**Comment by glenn2223** [comment] 2022-01-30 18:55
Duplicate of #62 

Unfortunately not. However, there is a postcss plugin that does do this. You could write your own script to run when a CSS file has been compiled

---

**Leading on from this**  
I have thought about allowing third party postcss plugins to allows thing like this. I'll have to do some more research and post my findings. However, if implemented, it won't be for some time

**Closed by glenn2223** 2022-01-30 18:55 UTC
