### ISSUE TITLE
No progress beyond `Working on it`

### ISSUE THREAD

**Issue by GPac65** [glenn2223/vscode-live-sass-compiler#73] opened 2021-04-28 08:48 UTC
When enabling watch sass, just reports working on it and no output to terminal window as normal. Have been using with no problems till today. 

Have a colleague who was using old V3 of this extension , who was working on same project. 

Disabled V5.0.2 in my visual studio and switched back to V3 and it works.

Have tried removing and reinstalling , but no success

**Comment by glenn2223** [comment] 2021-04-28 09:17
Sorry you're have a problem @GPac65 . Got a few questions.

 Does the status bar report Success or Error?

Is there an error in the bottom right corner?

Does setting `showOutputOn` to `"Information"` give you the expected output?

Do you still have the same problem in v4.4?

**Comment by GPac65** [comment] 2021-04-28 09:57
status bar reports 'working on it'

No error  - bottom right

The setting showOutputOn to "Information" has no effect as does not pass 'working on it' stage. Normally would see output in live sass compile terminal window.

I have been using V5 for a while no -issues, wonder if issue is colleague working on same project using V3 is causing some problem?

**Comment by GPac65** [comment] 2021-04-28 09:58
same issue when rolling back to v4.4

**Comment by glenn2223** [comment] 2021-04-28 12:34
Thanks for confirming all that for me.

Could you please set `showOutputOn` to `"Trace"` and paste the output here. I may also need a copy of the SASS file you're trying to save - but let's see what that outputs first.

**Comment by glenn2223** [comment] 2021-04-28 12:42
Just had a chance to re-read your comment and noticed this

> I have been using V5 for a while no -issues, wonder if issue is colleague working on same project using V3 is causing some problem?

This may be a possibility actually. I changed some settings and I may not have configured it to handle some old settings that may have carried through.

Can you send me a screenshot of the settings open in your (v5) - this should hopefully flag some settings with an orange underline.

**Comment by GPac65** [comment] 2021-04-28 14:27
![Screenshot 2021-04-28 at 15 26 39](https://user-images.githubusercontent.com/80251447/116420706-25c06c00-a836-11eb-887d-02d91902a50c.png)

**Comment by glenn2223** [comment] 2021-04-28 14:33
Thanks for the screenshot. Those two settings are fine - the others use the defaults - so it should all be working as expected.

Back to me earlier comment then. --> *Could you please set `showOutputOn` to `"Trace"` and paste the output here. I may also need a copy of the SASS file you're trying to save - but let's see what that outputs first.*

**Comment by glenn2223** [comment] 2021-05-01 21:32
Hey @GPac65,

Can you please send me the information that I requested? Thanks.

**Comment by glenn2223** [comment] 2021-05-05 16:42
Closing as more info is required

**Comment by glenn2223** [comment] 2021-05-05 16:43
If you still have the issue then please include the previously requested information and reopen the issue.

Thanks

**Comment by GPac65** [comment] 2021-05-07 10:18
apologies have been on holiday.

I have attached sass file causing issue . I have tracked it to line 103 

@extend p

If I uncomment this line then sass fails to compile, no errors output - just hangs 
[_page-track-record.sass.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6440805/_page-track-record.sass.zip)

**Comment by glenn2223** [comment] 2021-05-08 23:09
>apologies have been on holiday.

That's fine, hope you had a good time 😁

>I have attached sass file causing issue. I have tracked it to line 103
>`@extend` p
>If I uncomment this line then sass fails to compile, no errors output - just hangs

As you can see from the below project, mine compiles just fine  
[Issue 73 - Sample Project.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6446677/Issue.73.-.Sample.Project.zip)

Can you provide all the SASS files in the project, as well as your `settings.json` file?

Can you also send me the trace output - as per the instructions below:
1. Open your project
2. Copy `"liveSassCompile.settings.showOutputWindowOn": "Trace"` into your `settings.json` file
    If you don't have one:
    a. Create one in your `.vscode` folder
    b. Include the above text between some braces (`{ }`)
3. Save the file that has an issue compiling - this should output a large amount of text to the output window
4. Copy the output text and paste it into a comment here

---

**Side note:** This may be an issue with `dart-sass` itself, as the problem is with an `@extend` statement. The above should help rule out my extension as the cause. If it does, I will close this issue and then I will open a new issue in the `dart-sass` repo and link back here - hopefully, they can shed some light or fix the issue.

**Comment by glenn2223** [comment] 2021-05-17 15:36
I don't suppose you've had a chance yet @GPac65?

**Comment by glenn2223** [comment] 2021-05-19 21:21
> Is there a way to send files - so they remain private ?

Yes, you can! Just create a **private** repository, upload the files and add me as a contributor. I can then see your files and run some tests

**Comment by GPac65** [comment] 2021-05-19 23:13
Thanks you should have invite to private repo, with requested files and trace.

**Comment by glenn2223** [comment] 2021-05-20 00:38
Thanks for all this.

As I thought, the issue appears to lie with `dart-sass`. I have posted an issue on the private repo you shared with me.

**Comment by glenn2223** [comment] 2021-05-21 11:33
As this issue is being caused by dart-sass I have closed this issue.

**Closed by glenn2223** 2021-05-21 11:33 UTC
Labels: bug, info required
