### ISSUE TITLE
Invalid result when making css from Bootstrap4

### ISSUE THREAD

**Issue by Petr-200** [glenn2223/vscode-live-sass-compiler#232] opened 2022-10-28 19:25 UTC
A few day ago I switched from Live Sass Compiler from Ritwick Dey to your Live Sas Compiler. I have notices changes in result css file, that is produced from Bootstap-4.4.0 scss source.

for example in .form-control selector:
height: calc(1.5em + 0.75rem + 2px);
to:
height: calc(1.5em + 0.75rem2px);

Second plus sign is missing.

**Comment by glenn2223** [comment] 2022-10-29 14:30
Going to investigate this.

Are you using the whole bootstrap or including one of their modules?

**Comment by glenn2223** [comment] 2022-11-02 09:47
I had a compilation issue once but then I wasn't able to reproduce it when I came to testing. Don't know if there was some cache built by SASS that sorted it when I saved it the second time

Can you try saving the file again and see if this resolves your issue?

I'll be updating the SASS module soon, as there is something in their changelog that _may_ be a fix 🤷‍♂️. Sorry hectic time at the minute (with baby, uni, work 😩)

**Comment by glenn2223** [comment] 2023-01-24 09:56
Can you try [live-sass-5.5.2-alpha.3.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/10400812/live-sass-5.5.2-alpha.3.zip)

**Comment by glenn2223** [comment] 2023-02-07 13:05
Closing as info required. v6 is also available with a more recent version of SASS included

**Closed by glenn2223** 2023-02-07 13:05 UTC
Labels: bug, info required

**Comment by Petr-200** [comment] 2023-02-07 16:45
Sorry I replied to noreply email address. Error is still remaing - tested on your aplha version.

**Comment by Petr-200** [comment] 2023-02-07 16:46
![Snímek obrazovky pořízený 2023-01-25 10-41-49](https://user-images.githubusercontent.com/59543691/217308962-b7d1f204-63b3-4b2e-9716-41a90e9219a7.png)

**Comment by glenn2223** [comment] 2023-02-07 17:05
Using bootstrap 4.6.2, the issue is resolved.

Looks like it was an issue with bootstrap that was fixed between 4.4.0 and 4.6.2

**Comment by Petr-200** [comment] 2023-02-07 17:39
Hello Glenn,
I upgraded bootstrap to version 4.6.2 and this error disappeared.
Thank you Petr
