### ISSUE TITLE
Live sass compiler not working please help

### ISSUE THREAD

**Issue by Emanuele-Senis** [glenn2223/vscode-live-sass-compiler#144] opened 2022-01-03 18:49 UTC
Hello, live sass compiler has stopped working. What should I do?

**Comment by glenn2223** [comment] 2022-01-03 19:15
What do you mean by stopped working?

Does the"Watch Sass" text not show at the bottom? Do you get error messages?

**Comment by Emanuele-Senis** [comment] 2022-01-04 15:17
> What do you mean by stopped working?
> 
> Does the"Watch Sass" text not show at the bottom? Do you get error messages?

Hello @glenn2223 , I wanted to advise you that I think I have figured out why it didn't work. So, if in the margin property you put a clamp value it just gives and error and stops compiling, even if at the bottom right of the screen appears that sass is watching

**Comment by Emanuele-Senis** [comment] 2022-01-04 15:18
For example if you say margin top: clamp(0.5rem, 5vw - 1rem, 1rem); it doesn't compile it

**Comment by glenn2223** [comment] 2022-01-04 22:26
I don't think that is the cause, please refer to my _very_ simple sample project below

[Issue 144 - Sample Project.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7810733/Issue.144.-.Sample.Project.zip)

----

Sorry in advance for the barrage of questions! 😂

What made you think it was that. Did removing it resolve the issue?

Does the icon in the bottom right change to "Success" when you save?

What OS do you have?

Can you provide a zip of the project?

**Comment by glenn2223** [comment] 2022-01-10 23:02
Closing as more info required

**Closed by glenn2223** 2022-01-10 23:02 UTC
Labels: info required

**Comment by Emanuele-Senis** [comment] 2022-01-13 13:36
When I removed the clamp value of the margin it started compiling again writing success at the bottom right of the screen in vs code

**Comment by glenn2223** [comment] 2022-01-14 00:22
What's your OS (windows, mac, linux)?

Can you provide a zip of the project?

>... I remove both property and value they don't get removed

I'm aware of this issue. If you download a v5.2.0-alpha this is resolved
