### ISSUE TITLE
Compiler does not generate the sass built-in function correctly

### ISSUE THREAD

**Issue by murugappanrm** [glenn2223/vscode-live-sass-compiler#126] opened 2021-09-29 10:59 UTC
Hi,

When i used the sass:math module, and used one of the math.div function, compiler version 5.1.0 does not generate the css for the property and also generates an error css file. 

File containing the built in
![file with Builtin](https://user-images.githubusercontent.com/63133893/135254881-e600e536-e6cc-4ea1-8f7b-58e0c1029026.png)

generated CSS:
![generated css file](https://user-images.githubusercontent.com/63133893/135254946-b89a29d0-269d-4e34-872f-74f6bac12d36.png)

Please use the scss files in the attached zip file.
[shinobi.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7251234/shinobi.zip)

Also setting Show Output Window On: Debug is not working.

**Comment by glenn2223** [comment] 2021-09-29 21:28
Duplicate of #125

**Closed by glenn2223** 2021-09-29 21:28 UTC
