### ISSUE TITLE
Extension won't install

### ISSUE THREAD

**Issue by Fawaytish** [glenn2223/vscode-live-sass-compiler#54] opened 2021-04-03 11:00 UTC
After clicking install button on the markeplace, the extension won't install. It sometimes prompts me to reload vscode, but after reloading vscode, the extension is still not installed.
![bug](https://user-images.githubusercontent.com/25621690/113476520-433f2780-947c-11eb-9ec8-b4094d9b5658.gif)
I even tried clean installing the latest vscode, but to no avail. Version 4 installs just fine.

**Comment by kty0529** [comment] 2021-04-03 13:11
same issue

**Comment by kty0529** [comment] 2021-04-03 13:54
I solved it as a temporary measure by downloading and reinstalling 5.0.0-rc1.
Perhaps it seems that the problem in the 5.0.0-rc2.

**Comment by virtualgadjo** [comment] 2021-04-03 14:07
same here, waiting for rc3 :)

**Comment by glenn2223** [comment] 2021-04-03 14:41
Sorry about this. Can you try the below:
1. Visit [rc2 release here](https://github.com/glenn2223/vscode-live-sass-compiler/releases/tag/v5.0.0-rc.2)
2. Download the .vsix file
3. Drag it into the "Extensions" tab
    *Does this work? The version should read 5.0.0-rc.2*

If so I think it's an issue I reported [here](https://github.com/microsoft/vscode/issues/120389). The marketplace say they support SemVer versioning but they don't allow me to upload anything with non-numerics🤦‍♂️

I'll have to prevent the rc releases on the VS marketplace, which would be very annoying

**Comment by glenn2223** [comment] 2021-04-03 15:10
Managed to get to a computer and test this.

I can confirm the issue, it appears that the extension is being automatically uninstalled?? Very strange. I will add some info to the issue reported to Msft.

My suggestion above works as I thought it would. You may have to drop to v4.4.1 then drag the file into the "Extensions" tab

**Comment by glenn2223** [comment] 2021-04-03 15:50
> same here, waiting for rc3 :)

It should be up tonight!

~~However, I'm not sure how to release it with this issue 🤷‍♂️. I want it on the marketplace as I had alphas for ages and it's only when the preview went onto the marketplace that I actually got some consistent usage & feedback~~

I think I'll try to publish rc3 tonight as I did before (with a `5.0.0` tag). Hopefully this issue was a one off and there are no install issues next time

**Comment by glenn2223** [comment] 2021-04-03 23:12
Yeah, something is really wrong with VS Code's marketplace upload feature.

Just uploaded rc3. However, when I download it directly from the marketplace [here](https://marketplace.visualstudio.com/items?itemName=glenn2223.live-sass&ssr=false#version-history), the `package.json` says rc.2 which isn't even possible as I couldn't even upload one with an rc in the `package.json`. I'm so confused.

My last-ditch effort is trying to publish using CI. Hopefully, the issue is only on the website and by using the CI I can bypass it 🤞

**Comment by glenn2223** [comment] 2021-04-04 00:55
No luck with the vsce publish command (which CI would use), I get the same error as per the website

```
Publishing glenn2223.live-sass@5.0.0-rc.4...
ERROR  The version string '5.0.0-rc.4' doesn't conform to the requirements for a version. It must be one to four numbers in the range 0 to 2147483647, with each number seperated by a period. It must contain at least one non-zero number.
```

Looks like I'll have to wait for MS to fix the issue before releasing anything (that's not 100% okay to launch) on the marketplace

**Comment by jsaa** [comment] 2021-04-05 00:13
I'm not being able to install as well :(

**Comment by glenn2223** [comment] 2021-04-06 09:26
Obviously, it's not great having a broken extension on the marketplace.

I think that, once I have confirmed a resolution of issue 57, I will officially release v5. Any further issues will have to be addressed as patches (5.0.1, 5.0.2, etc.)

**Comment by glenn2223** [comment] 2021-04-06 22:18
Just dropped v5 (out of preview). Can someone please confirm that it's installed okay or I'll have to release a bump to fix the issue

Thanks

**Comment by jsaa** [comment] 2021-04-06 22:48
> Just dropped v5 (out of preview). Can someone please confirm that it's installed okay or I'll have to release a bump to fix the issue
> 
> Thanks

Bad news, I'm still with the same issue. But, FYI, if I DON'T reload the VS Code, the extension works just fine. In the other hand, if I close it, I have to install it all over again.

**Comment by glenn2223** [comment] 2021-04-07 08:34
> Bad news, I'm still with the same issue.

Thanks, I thought as much.

---

I have released v5.0.1. It works fine for me, but could someone else please confirm? I can then close this issue.

Thanks again

**Comment by jsaa** [comment] 2021-04-07 13:29
> > Bad news, I'm still with the same issue.
> 
> Thanks, I thought as much.
> 
> I have released v5.0.1. It works fine for me, but could someone else please confirm? I can then close this issue.
> 
> Thanks again

It worked!!!! Great job!

**Comment by kty0529** [comment] 2021-04-08 01:03
Works fine for me too!
Thanks!! :-)

**Comment by glenn2223** [comment] 2021-04-08 21:36
Thank you for confirming 😁

**Closed by glenn2223** 2021-04-08 21:36 UTC
