### ISSUE TITLE
not supporting new @use and @forward

### ISSUE THREAD

**Issue by AnkitJ393** [glenn2223/vscode-live-sass-compiler#101] opened 2021-07-01 12:10 UTC
Since @import is deprecated instead @use is taking its place .I thought it will support @use but it doesn't

**Comment by glenn2223** [comment] 2021-07-02 00:08
This extension does support this feature. Please ensure that you are using it correctly

Closing as duplicate of #79

**Closed by glenn2223** 2021-07-02 00:08 UTC
