### ISSUE TITLE
showOutputWindowOn to "none" gives no effect

### ISSUE THREAD

**Issue by tkitka** [glenn2223/vscode-live-sass-compiler#330] opened 2023-10-04 07:53 UTC
VScode output panel still opens on compilation error even if the parameter "liveSassCompile.settings.showOutputWindowOn" is set to "none".

**Comment by glenn2223** [comment] 2023-10-04 09:03
Have you tired "None", it's an enum type and there may be case-sensitivity

https://github.com/glenn2223/vscode-live-sass-compiler/blob/4ba1cba8ca8db1289a02182abce25d89cf5d9e49/package.json#L293-L300

**Comment by tkitka** [comment] 2023-10-04 11:32
I have this in the settings.json:
  "liveSassCompile.settings.showOutputWindowOn": "None",
  "liveSassCompile.settings.watchOnLaunch": true,

**Comment by glenn2223** [comment] 2023-10-04 16:25
I'm sorry, but I'm not able to reproduce your issue.

If the output is already open it will not automatically close it. After you close it - and with the setting set as you stated - it will not open again unless there is a critical issue with the extension.

It's also worth checking that the setting isn't being overwritten at a workspace level (if the setting is greyed out where you're editing it then it's not being changed)

**Comment by glenn2223** [comment] 2023-10-10 00:35
Any luck @tkitka? 

It's also worth mentioning that VS Code gets into weird states sometimes. I have had other people report issues that suddenly go away or are corrected after they clear the extension data/reinstall the extension

**Comment by tkitka** [comment] 2023-10-10 14:20
Maby the problem is autosave feature:
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 500,

The file is saving during typing. The saved file with unfinished css code leads to an error -> output is opened.

**Comment by glenn2223** [comment] 2023-11-22 22:58
Glad you identified your issue. You can actually specify different settings for specific languages in VS Code<sup>[[ref](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings)]</sup>. So, your SASS files can be opted out of autosaving

---

Closing as out of scope - not an issue with the extension directly but the settings/setup. Though will link this to #326, just so I can keep this in mind during that development phase

**Closed by glenn2223** 2023-11-22 22:58 UTC
