### ISSUE TITLE
How to change from 2 spaces to 4 spaces in generated scss-css file? 

### ISSUE THREAD

**Issue by scarecrow2k6** [glenn2223/vscode-live-sass-compiler#110] opened 2021-07-29 03:10 UTC
I am super new to coding in general. I have looked everywhere but could not find anything to "fix" my issue. The generated CSS file uses 2 spaces for indentation, just wondering how I can change it so that when the CSS is generated, it has 4 spaces for indentation. Thanks.

**Comment by glenn2223** [comment] 2021-07-29 09:59
This is going to be available in v5.1. However, you can use it now by downloading the alpha - find out how here #84

---

Closing as duplicate of #82

**Closed by glenn2223** 2021-07-29 09:59 UTC

**Comment by glenn2223** [comment] 2021-07-29 10:01
FYI: if you want to reduce the file size, I'd suggest using one tab rather than 4 spaces

**Comment by scarecrow2k6** [comment] 2021-07-29 12:35
> 
> 
> FYI: if you want to reduce the file size, I'd suggest using one tab rather than 4 spaces

Thank you for clarifying the above issue and the tab-space thing. I use tab but to explain myself I mentioned 4 spaces, didn't know there is a difference technically. Is there an option for tab indentation in the current build?

**Comment by glenn2223** [comment] 2021-07-30 10:48
Glad it's working for you 😁

>didn't know there is a difference technically

Yeah, there is! Let's go if track a little 😂

A tab and space both require the same amount of bits to represent that character. By having 4 spaces you need those bits repeated 4 times - whereas a tab just needs the one. This soon adds up in a formatted CSS file.

Plus there's the advantage that some editors let users choose what their tab size is - rather than forcing 4 spaces on them 🤣
