### ISSUE TITLE
Double sass in path in map file

### ISSUE THREAD

**Issue by dawidmachon** [glenn2223/vscode-live-sass-compiler#135] opened 2021-11-21 02:11 UTC
### Original post

Hi Guys,
Could you help me a bit to understand why compiler generating wrong source path in map file?

I have nested folder with scss and different one for css. CSS files are generated fine and in proper place, but my map file contains wrong path inside.

Part of wrong map file _style.css.map_:
```
{"version":3,"sources":["../sass/sass/hold/style.scss","../sass/hold/style.scss","../sass/sass/bootstrap/mixins/_vendor-prefixes.scss","../sass/sass/bootstrap/_variables.scss"],"names":[],"mappings":.........}
```

I want to avoid this double `/sass/sass/` in first path. Could you help me a bit?

Here is my structure:
![image](https://user-images.githubusercontent.com/44931854/142746583-0073377d-875b-447b-ac90-b24f7bdcd742.png)

My settings:
```
    "liveSassCompile.settings.formats": [
        // This is the default.
        {
            "format": "expanded",
            "extensionName": ".css",
    
            // null for all three -> denotes the same path as the SASS file
            "savePath": "themes/hold/css/",
            "savePathSegmentKeys": null,
            "savePathReplaceSegmentsWith": null
        }
```

---

### Tasks for 5.2 release

- [x] Find cause
- [x] Apply fix

**Comment by glenn2223** [comment] 2021-11-22 12:32
How very strange! I ran my own test and was able to reproduce it. It seems to be an issue with autoprefixer so I have opened an issue there - postcss/autoprefixer#1437

**Comment by dawidmachon** [comment] 2021-11-22 13:49
Thanks for collaboration on it! I saw respond from Andrey (ai):

> The problem is that if you take from option and add sassMap.source to it, you will not get path to the Sass source.
> 
> It leads to sources duplication.
> 
> You need to fix paths, but I can’t help you where exactly is a mistake.

Do you find time to look into it? ;)

**Comment by glenn2223** [comment] 2021-11-24 12:53
I will fix it so it won't include the duplicate/incorrect SASS path. However, it will always include a reference to the CSS file itself (in your case `style.css`) which, according to [this comment](https://github.com/postcss/autoprefixer/issues/1437#issuecomment-977841535), they will not be fixing/addressing.

**Comment by dawidmachon** [comment] 2021-11-24 17:41
Okay, so what needs to be done manually? 

> However, it will always include a reference to the CSS file itself (in your case style.css)

What that mean for me?

Thanks for your time and help!

**Comment by glenn2223** [comment] 2021-11-25 10:39
>Okay, so what needs to be done manually?

Nothing, I'll push a new release soon. I have already applied the fix to the `ahead` branch ready to publish. If you wanted to remove the unnecessary binding then you'd have to build a script that removes them once a `.css.map` file is saved

>What that mean for me?

It just means that without autoprefixer a map file will be interpreted as below (the column on the right is where the browser would take you if you wanted to see the source of the item on the left)

![image](https://user-images.githubusercontent.com/33450392/143424984-6d795f18-6846-4a5d-841d-dc8ad6bbe37b.png)

And with autoprefixer applied it will instead be interpreted like this

![image](https://user-images.githubusercontent.com/33450392/143425428-76e35d5a-e6e2-44e0-85e3-2be6c818b987.png)

What this basically means is that the new map file will be unnecessarily bigger to reflect the unmapped lines that the SASS' map doesn't include (as the browser will never interpret/care about them).

I hope this all makes sence

**Comment by dawidmachon** [comment] 2021-11-25 22:39
Yes, I am totally new to Sass things and doing them casually, so I spot this issue totally not expected ;)

Thanks for your deep analysis and fix! I appreciate it!

**Closed** 2022-01-10 23:50 UTC

**Comment by DvdRom87** [comment] 2022-02-18 07:32
Hi, i just wanted to ask when the update is pushed?
I really would like this issue to be fixed 😬

Thanks for the great work.

**Comment by glenn2223** [comment] 2022-02-21 22:56
Hey @DvdRom87,

Sorry for the delay. It has been a bit of a crazy couple of months - moving, new baby, work, uni studies - which has pushed these things to the back burner.

I was also waiting on #151 to confirm that the fix worked, this way I can push it in this release. But the change should fix the top-level problem and more work may be needed to address their other concerns, so I'll push an official release tonight.
