### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by billpebert** [glenn2223/vscode-live-sass-compiler#36] opened 2021-02-09 03:21 UTC
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `4.4.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\bpgpo\AppData\Local\Temp\glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by glenn2223** [comment] 2021-02-09 09:06
Hi @billpebert,

Sorry to hear you're having this issue, although I'm pretty sure I know what the issue is.

I'm aware of a bottleneck issue with our glob pattern matcher in larger projects. This will be fixed in v5 when we move from `glob` to `fdir` (ref: #27).

Can you please see the below and answer my questions. If my suspicions are correct then the `forceBaseDirectory` setting will help.

---

>⚠️ Make sure to attach this file from your home-directory:
>⚠️`c:\Users\bpgpo\AppData\Local\Temp\glenn2223.live-sass-unresponsive.cpuprofile.txt`

I'd need this file to help debug the issue. Please visit the above path on your local machine and attach it to this issue

---

Please can you answer the below, I have included my suspicions after each question
- Is this when saving or when VS Code loads? 
  - *When you save all files (i.e. from the command `liveSass.command.oneTimeCompileSass` or saving a partial file)*
- How many files (total, including non-sass) does your workspace have?
  - *Thousands*
- How many of those files are SASS files?
  - *Less than 100*
- Have you tried the [`forceBaseDirectory`](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md) setting?
  - *Not yet*

**Comment by glenn2223** [comment] 2021-02-16 23:17
Closing as need more info

**Closed by glenn2223** 2021-02-16 23:17 UTC
Labels: info required
