### ISSUE TITLE
Compiling takes a long time since last week

### ISSUE THREAD

**Issue by BoostCreatorsGit** [glenn2223/vscode-live-sass-compiler#289] opened 2023-04-03 07:20 UTC
Since last week the compiling takes a long time when saving my sass file. It also shows a check with the text 'Working on it..' is in geen. After a second it urns to success.

**Comment by glenn2223** [comment] 2023-04-03 23:46
This does seem to tie in with a recent [sass/dart-sass](https://github.com/sass/dart-sass)/extension update. 

- Does rolling back to the previous version resolve the issue? 
- Has there been any other code changes that might have caused the problem - again, that you could possibly roll-back for testing? 
- Does the setting the new compiler `useNewCompiler` setting help at all?

The compilation aspect of this application is actually preformed by the before mentioned [sass/dart-sass](sass/dart-sass) package. If you can confirm the SASS update is the cause then creating an issue with a sample project over at that repo should get this issue resolved.

**Comment by BoostCreatorsGit** [comment] 2023-04-05 15:15
Hi Glenn,

Roling back to a previous version makes the compiler quick again.

Van: Glenn ***@***.***>
Datum: dinsdag, 4 april 2023 om 01:46
Aan: glenn2223/vscode-live-sass-compiler ***@***.***>
CC: Support | Boost Creators ***@***.***>, Author ***@***.***>
Onderwerp: Re: [glenn2223/vscode-live-sass-compiler] Compiling takes a long time since last week (Issue #289)

This does seem to tie in with a recent sass/dart-sass<https://github.com/sass/dart-sass>/extension update.

  *   Does rolling back to the previous version resolve the issue?
  *   Has there been any other code changes that might have caused the problem - again, that you could possibly roll-back for testing?
  *   Does the setting the new compiler useNewCompiler setting help at all?

The compilation aspect of this application is actually preformed by the before mentioned sass/dart-sass package. If you can confirm the SASS update is the cause then creating an issue with a sample project over at that repo should get this issue resolved.

**Comment by glenn2223** [comment] 2023-04-06 22:00
In that case you'd be best creating a sample project where you can replicate the problem and open an issue over at dart-sass

If they resolve the issue let me know and I will update the SASS reference

---

Closing as out of scope

**Closed by glenn2223** 2023-04-06 22:00 UTC

**Comment by glenn2223** [comment] 2023-04-09 22:19
v6.0.5 includes a SASS v1.61.0 which states

>Fix remaining cases for the performance regression introduced in 1.59.0

Please check it v6.0.5 is quicker
