### ISSUE TITLE
When my SCSS file is automatically compiled, it also recompiles every SCSS file in my entire workspace

### ISSUE THREAD

**Issue by gavin310** [glenn2223/vscode-live-sass-compiler#31] opened 2021-02-03 09:18 UTC
I'm not sure what I can provide here. My SCSS file contains @import statements that import files, but only files residing in the current folder. When I saved my changes it searched for every single SCSS file in my workspace (which contains a WordPress themes folder and the plugins folder) and recompiled them. In total it recompiled about 150 SCSS files throughout my project.

If you want I could send you my SCSS files to a personal message.

**Comment by gavin310** [comment] 2021-02-03 09:20
Actually it recompiles every SCSS when I click "Watch Sass".

**Comment by glenn2223** [comment] 2021-02-03 09:28
When the extension was first created by Ritwickdey his initial thought was to keep it simple. This meant that when a partial file (that's any file beginning with a `_`) processes all files within the document. You can use the various setting to choose which files to compile.

Examples:
- `forceBaseDirectory`  when you only want to compile a specific folder
- `includeFiles` when you only want specific files to be processed anytime a partial is saved (accepts glob patterns)
- `excludeFiles` to exclude based on glob patterns

>Actually it recompiles every SCSS file when I click "Watch Sass" and also when I make changes and save.

This can be disabled with the `compileOnWatch` setting

Can you confirm that this is what your problem is/you're after => #17  
If so, I'll close this as duplicate and re-open the original issue with more weight behind it

**Comment by gavin310** [comment] 2021-02-03 09:39
Oooh ok. Let me just provide a quick example so I can make sure this is correct. I was a bit surprised when 150 SCSS files rendered.

Here's a sample structure of my workspace:

```
- theme
  - themeName
    - css
	  - main.scss
	- js
	- img
- plugins
    - someRandomPlugin
	  - assets
	  	- css
		  - src
		  	- styles.scss
	- anotherPlugin
	  - styles.scss
	- yoastSEO
	  - folders
	    - lots-of-folders
		  - a-deep-scss-file.scss
	- myPlugin
	  - assets
	    - main.scss
		  - _includeFile.scss
		  - _anotherInclude.scss (this is the file I'm saving)
```
So when I saved "_anotherInclude.scss" it rendered every single SCSS file that's in that tree.

Is that really what it's supposed to do with the default settings?

**Comment by glenn2223** [comment] 2021-02-03 10:02
That's right, every file that's not a partial will be processed (based on default settings), as per the below

```
- theme
  - themeName
    - css
	  - main.scss <-- THIS ONE
	- js
	- img
- plugins
    - someRandomPlugin
	  - assets
	  	- css
		  - src
		  	- styles.scss <-- THIS ONE
	- anotherPlugin
	  - styles.scss <-- THIS ONE
	- yoastSEO
	  - folders
	    - lots-of-folders
		  - a-deep-scss-file.scss <-- THIS ONE
	- myPlugin
	  - assets
	    - main.scss <-- THIS ONE
		  - _includeFile.scss
		  - _anotherInclude.scss (this is the file I'm saving)
```

When he initially created the extension it was designed for small packages of SCSS, not those embedded in larger projects. Hence why, with me (and the community) moving this project forward, we now have a `forceBaseDirectory` attribute. As well as moving towards a save process that knows the links between files (as per #17)

**Comment by gavin310** [comment] 2021-02-03 10:48
Ok that actually makes sense. Thanks a lot for the explanation!

**Comment by glenn2223** [comment] 2021-02-03 10:54
No worries, glad I could help

Closing as (essentially) a duplicate of #17

**Closed by glenn2223** 2021-02-03 10:54 UTC
