### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kevinamrulloh** [glenn2223/vscode-live-sass-compiler#38] opened 2021-02-22 04:28 UTC
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `4.4.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\KEVINA~1\AppData\Local\Temp\glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by glenn2223** [comment] 2021-02-22 09:19
Hi @kevinamrulloh,

First of all, so I can debug the issue, can you please attach the file specified in your opening comment
>⚠️c:\Users\KEVINA~1\AppData\Local\Temp\glenn2223.live-sass-unresponsive.cpuprofile.txt

---

If the issue is on load, then Live Server is causing the delay and you need to download the v5 alpha (currently [v5.alpha-1](https://github.com/glenn2223/vscode-live-sass-compiler/blob/v5/live-sass-5.0.0-alpha.1.vsix)) and drag it into the `Extensions` tab on VS Code.

However, if the issue occurs when you save a partial file then I'd suggest using the `forceBaseDirectory` setting (last setting [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/96d200e6cda54fec0201c3daf14ab0310b623dc2/docs/settings.md))

---

Please let me know if this doesn't resolve your issue

**Comment by kevinamrulloh** [comment] 2021-02-22 12:39
[ritwickdey.live-sass-unresponsive.cpuprofile.txt](https://github.com/glenn2223/vscode-live-sass-compiler/files/6021952/ritwickdey.live-sass-unresponsive.cpuprofile.txt)
now i am using v5 aplha and this is the file

**Comment by glenn2223** [comment] 2021-02-22 13:12
The file you included is from Ritwick's original extension. Mine should read `glenn2223.live-sass...`

Also, just so it's clear. Did the update help?

**Comment by glenn2223** [comment] 2021-02-28 23:55
Closing - more info required

**Closed by glenn2223** 2021-02-28 23:55 UTC
Labels: info required
